/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EncryptionDetailsService } from "../encryptionDetails.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EncryptionDetailsCreateInput } from "./EncryptionDetailsCreateInput";
import { EncryptionDetails } from "./EncryptionDetails";
import { EncryptionDetailsFindManyArgs } from "./EncryptionDetailsFindManyArgs";
import { EncryptionDetailsWhereUniqueInput } from "./EncryptionDetailsWhereUniqueInput";
import { EncryptionDetailsUpdateInput } from "./EncryptionDetailsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EncryptionDetailsControllerBase {
  constructor(
    protected readonly service: EncryptionDetailsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EncryptionDetails })
  @nestAccessControl.UseRoles({
    resource: "EncryptionDetails",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEncryptionDetails(
    @common.Body() data: EncryptionDetailsCreateInput
  ): Promise<EncryptionDetails> {
    return await this.service.createEncryptionDetails({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        algorithm: true,
        createdAt: true,
        id: true,
        key: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EncryptionDetails] })
  @ApiNestedQuery(EncryptionDetailsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EncryptionDetails",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async encryptionDetailsItems(
    @common.Req() request: Request
  ): Promise<EncryptionDetails[]> {
    const args = plainToClass(EncryptionDetailsFindManyArgs, request.query);
    return this.service.encryptionDetailsItems({
      ...args,
      select: {
        algorithm: true,
        createdAt: true,
        id: true,
        key: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EncryptionDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EncryptionDetails",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async encryptionDetails(
    @common.Param() params: EncryptionDetailsWhereUniqueInput
  ): Promise<EncryptionDetails | null> {
    const result = await this.service.encryptionDetails({
      where: params,
      select: {
        algorithm: true,
        createdAt: true,
        id: true,
        key: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EncryptionDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EncryptionDetails",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEncryptionDetails(
    @common.Param() params: EncryptionDetailsWhereUniqueInput,
    @common.Body() data: EncryptionDetailsUpdateInput
  ): Promise<EncryptionDetails | null> {
    try {
      return await this.service.updateEncryptionDetails({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          algorithm: true,
          createdAt: true,
          id: true,
          key: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EncryptionDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EncryptionDetails",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEncryptionDetails(
    @common.Param() params: EncryptionDetailsWhereUniqueInput
  ): Promise<EncryptionDetails | null> {
    try {
      return await this.service.deleteEncryptionDetails({
        where: params,
        select: {
          algorithm: true,
          createdAt: true,
          id: true,
          key: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
