/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PasswordEntry } from "./PasswordEntry";
import { PasswordEntryCountArgs } from "./PasswordEntryCountArgs";
import { PasswordEntryFindManyArgs } from "./PasswordEntryFindManyArgs";
import { PasswordEntryFindUniqueArgs } from "./PasswordEntryFindUniqueArgs";
import { CreatePasswordEntryArgs } from "./CreatePasswordEntryArgs";
import { UpdatePasswordEntryArgs } from "./UpdatePasswordEntryArgs";
import { DeletePasswordEntryArgs } from "./DeletePasswordEntryArgs";
import { User } from "../../user/base/User";
import { PasswordEntryService } from "../passwordEntry.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PasswordEntry)
export class PasswordEntryResolverBase {
  constructor(
    protected readonly service: PasswordEntryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PasswordEntry",
    action: "read",
    possession: "any",
  })
  async _passwordEntriesMeta(
    @graphql.Args() args: PasswordEntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PasswordEntry])
  @nestAccessControl.UseRoles({
    resource: "PasswordEntry",
    action: "read",
    possession: "any",
  })
  async passwordEntries(
    @graphql.Args() args: PasswordEntryFindManyArgs
  ): Promise<PasswordEntry[]> {
    return this.service.passwordEntries(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PasswordEntry, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PasswordEntry",
    action: "read",
    possession: "own",
  })
  async passwordEntry(
    @graphql.Args() args: PasswordEntryFindUniqueArgs
  ): Promise<PasswordEntry | null> {
    const result = await this.service.passwordEntry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PasswordEntry)
  @nestAccessControl.UseRoles({
    resource: "PasswordEntry",
    action: "create",
    possession: "any",
  })
  async createPasswordEntry(
    @graphql.Args() args: CreatePasswordEntryArgs
  ): Promise<PasswordEntry> {
    return await this.service.createPasswordEntry({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PasswordEntry)
  @nestAccessControl.UseRoles({
    resource: "PasswordEntry",
    action: "update",
    possession: "any",
  })
  async updatePasswordEntry(
    @graphql.Args() args: UpdatePasswordEntryArgs
  ): Promise<PasswordEntry | null> {
    try {
      return await this.service.updatePasswordEntry({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PasswordEntry)
  @nestAccessControl.UseRoles({
    resource: "PasswordEntry",
    action: "delete",
    possession: "any",
  })
  async deletePasswordEntry(
    @graphql.Args() args: DeletePasswordEntryArgs
  ): Promise<PasswordEntry | null> {
    try {
      return await this.service.deletePasswordEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: PasswordEntry): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
